syntax enable "make colorscheme work on mac
colorscheme jellybeans

"start where last edited
au BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "norm g`\"" |
\ endif

set number relativenumber  "line number on the left
set autoindent      "autoindent
set hlsearch        "highlight search with / or ?
set ignorecase      "ignore case for search
set incsearch       "show search result for input character
set showmatch       "highlight matching brackets
set mouse=a         "allow mouse
set ts=4            "tap size
set sw=4            "shift width for use with >, <, or =
set expandtab       "spaces instead of tabs; `:retab` to change taps to spaces
set sts=4           "make spaces feel like tabs (like deleting)
set colorcolumn=80  "show vertical line at column 80
set nowrap          "no wraparound trailing characters
set scrolloff=99999 "put cursor always in center
set list            "make whitespaces visible
"set listchars=tab:>-,trail:~,extends:>,precedes:<
set listchars=tab:»\ ,trail:·,extends:>,precedes:<
set nostartofline   "keep column position when c-u or c-d


"display cursorline
set cursorline
set cursorcolumn
"autocmd insertenter * set nocursorline
"autocmd insertleave * set cursorline
"autocmd insertenter * set nocursorcolumn
"autocmd insertleave * set cursorcolumn

"autosave
"autocmd TextChanged,TextChangedI <buffer> silent write

inoremap jk <esc>

inoremap jk <esc>
nnoremap H 5j
"nnoremap J 5j
"nnoremap K 5k
nnoremap L 5k
vnoremap H 5j
"jkvnoremap J 5j
"vnoremap K 5k
vnoremap L 5k



